version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6g -Xmx6g"
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ~/elastic:/usr/share/elasticsearch/data
    networks:
      elastic:
        aliases:
         - es
    healthcheck:
      test: ["CMD", "curl", "-f", "http://es:9200"]
      interval: 1s
      timeout: 1s
      retries: 25
    ports:
      - 9200:9200

  snowstorm:
    image: snomedinternational/snowstorm:latest
    container_name: snowstorm
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: java -jar target/snowstorm-1.0.0-SNAPSHOT.jar --elasticsearch.urls=http://es:9200 --delete-indices --import=/opt/SnomedCT_InternationalRF2_PRODUCTION_20180131T120000Z.zip
    networks:
      - elastic
    volumes:
      -  ~/releases:/opt
    ports:
      - 8080:8080

networks:
  elastic:
